// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prickle.Infrastructure.Database;

#nullable disable

namespace Prickle.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217164151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prickle.Domain.Containers.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageIsometricUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_isometric_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<float>("Volume")
                        .HasColumnType("real")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_containers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_containers_name");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Decorations.Decoration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageIsometricUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_isometric_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_decorations");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_decorations_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_decorations_name");

                    b.ToTable("decorations", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Plants.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HumidityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("humidity_level");

                    b.Property<string>("ImageIsometricUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_isometric_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<int>("ItemMaxSize")
                        .HasColumnType("integer")
                        .HasColumnName("item_max_size");

                    b.Property<int>("LightLevel")
                        .HasColumnType("integer")
                        .HasColumnName("light_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameLatin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_latin");

                    b.Property<Guid>("SoilFormulaId")
                        .HasColumnType("uuid")
                        .HasColumnName("soil_formula_id");

                    b.Property<int>("WaterNeed")
                        .HasColumnType("integer")
                        .HasColumnName("water_need");

                    b.HasKey("Id")
                        .HasName("pk_plants");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_plants_name");

                    b.HasIndex("NameLatin")
                        .HasDatabaseName("ix_plants_name_latin");

                    b.HasIndex("SoilFormulaId")
                        .HasDatabaseName("ix_plants_soil_formula_id");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<byte[]>("Preview")
                        .HasColumnType("BYTEA")
                        .HasColumnName("preview");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_projects_container_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_projects_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_projects_user_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Projects.ProjectItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<int>("PosX")
                        .HasColumnType("integer")
                        .HasColumnName("pos_x");

                    b.Property<int>("PosY")
                        .HasColumnType("integer")
                        .HasColumnName("pos_y");

                    b.Property<int>("PosZ")
                        .HasColumnType("integer")
                        .HasColumnName("pos_z");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_items");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_project_items_item_type");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_items_project_id");

                    b.ToTable("project_items", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Soil.SoilFormulas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_soil_formulas");

                    b.ToTable("soil_formulas", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Soil.SoilType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_soil_types");

                    b.ToTable("soil_types", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Soil.SoilTypeSoilFormula", b =>
                {
                    b.Property<Guid>("SoilFormulaId")
                        .HasColumnType("uuid")
                        .HasColumnName("soil_formula_id");

                    b.Property<int>("SoilTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("soil_type_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer")
                        .HasColumnName("percentage");

                    b.HasKey("SoilFormulaId", "SoilTypeId", "Order")
                        .HasName("pk_soil_type_soil_formulas");

                    b.HasIndex("SoilTypeId")
                        .HasDatabaseName("ix_soil_type_soil_formulas_soil_type_id");

                    b.ToTable("soil_type_soil_formulas", (string)null);
                });

            modelBuilder.Entity("Prickle.Domain.Plants.Plant", b =>
                {
                    b.HasOne("Prickle.Domain.Soil.SoilFormulas", null)
                        .WithMany()
                        .HasForeignKey("SoilFormulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plants_soil_formulas_soil_formula_id");
                });

            modelBuilder.Entity("Prickle.Domain.Projects.Project", b =>
                {
                    b.HasOne("Prickle.Domain.Containers.Container", null)
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_containers_container_id");
                });

            modelBuilder.Entity("Prickle.Domain.Projects.ProjectItem", b =>
                {
                    b.HasOne("Prickle.Domain.Projects.Project", null)
                        .WithMany("Items")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_items_projects_project_id");
                });

            modelBuilder.Entity("Prickle.Domain.Soil.SoilTypeSoilFormula", b =>
                {
                    b.HasOne("Prickle.Domain.Soil.SoilFormulas", null)
                        .WithMany("Formula")
                        .HasForeignKey("SoilFormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_soil_type_soil_formulas_soil_formulas_soil_formula_id");

                    b.HasOne("Prickle.Domain.Soil.SoilType", null)
                        .WithMany()
                        .HasForeignKey("SoilTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_soil_type_soil_formulas_soil_types_soil_type_id");
                });

            modelBuilder.Entity("Prickle.Domain.Projects.Project", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Prickle.Domain.Soil.SoilFormulas", b =>
                {
                    b.Navigation("Formula");
                });
#pragma warning restore 612, 618
        }
    }
}
